<template>
  <div id="v_appManage">

    <h4>Authorization</h4>
    <hr/>
    <p>Create a "Log In" link sending the user to:</p>
    <textarea class="form-control" rows="3" readonly>https://this-server.com/oauth?vendor_id=[vendor_id]&redirect_uri=[redirect_uri]&scope=[scope]&state=[state]</textarea>
    <br/>
    <ul>
      <li><b>vendor_id</b> - The user_id of the vendor who's requesting permission</li>
      <li><b>redirect_uri</b> - The URI to return the user to after authorization is complete</li>
      <li><b>scope</b> - Values indicating which parts of the user's account you wish to access</li>
      <li><b>state</b> - A random string generated by your application, which you'll verify later</li>
    </ul>
    <p>The user sees the authorization prompt</p>
    <img width="100%" src="https://aaronparecki.com/oauth-2-simplified/oauth-authorization-prompt.png"/>
    <p>If the user clicks "Allow," the service redirects the user back to the vendor's site, indicated by the redirect_uri, with an access token</p>
    <textarea class="form-control" rows="1" readonly>https://vendor-app.com/cb?accessToken=[accessToken]&state=[state]</textarea>
    <br/>
    <ul>
      <li><b>accessToken</b> - The server returns the access token in the query string</li>
      <li><b>state</b> - The server returns the same state value that you passed earlier</li>
    </ul>
    <p>
      The vendor should first compare this state value to ensure it matches the one it started with.
      You can typically store the state value in a cookie or session, and compare it when the user comes back.
      This ensures your redirection endpoint isn't able to be tricked into attempting to exchange arbitrary
      access codes.
    </p>

    <h4>Token Exchange</h4>
    <hr/>
    <p>The vendor exchanges the access token for the user's tokens:</p>
    <textarea class="form-control" rows="5" readonly>
      HEADER authorization: [authToken]
      POST https://this-server.com/newVendorAuthToken
  accessToken=[accessToken]&
  redirect_uri=[redirect_uri]&
  scope=[scope]</textarea>
    <br/>
    <ul>
      <li><b>authToken</b> - The vendor's authToken generated from the newApiAuthToken endpoint using their API key</li>
      <li><b>accessToken</b> - This is the accessToken you received in the query string</li>
      <li><b>redirect_uri</b> - Must be identical to the redirect URI provided in the original link</li>
      <li><b>scope</b> - Must be identical to the scope provided in the original link</li>
    </ul>
    <p>The server replies with the user's authToken and refreshToken</p>
    <a href="https://aaronparecki.com/oauth-2-simplified/">To read more about OAuth 2 protocol, follow this link</a>

  </div>
</template>


<style lang="scss" rel="stylesheet/scss">
  #v_appManage {

  }
</style>
